# Generated by Django 3.1.3 on 2020-12-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='s'),
            preserve_default=False,
        ),
    ]
