# Generated by Django 3.1.3 on 2021-02-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_service_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_register',
            name='status',
            field=models.CharField(choices=[('Registerd', 'Registerd'), ('Inspectig', 'Inspectig'), ('Compleated', 'Compleated')], max_length=20, null=True),
        ),
    ]
